### PR TITLE
Fix avconv is not available in buster #600

### PR DESCRIPTION
**Pull request by guysoft**

### CODE REVIEW

**Comment by guysoft** [comment]
FYI @foosel

**Comment by foosel** [comment]
No veto from my side, this whole avconv stuff was a weird quirk anyhow that got introduced years ago and apparently now rolled back.

**Comment by guysoft** [comment]
Reported to have worked at: https://community.octoprint.org/t/raspberry-pi-4-is-out/10332/242

**Comment by SkullKill** [comment]
yes, correct, 

settings > webcam & Timelapse > Path to FFMPEG
change from
/usr/bin/avconv
to
/usr/bin/ffmpeg

works.

will report any other issues i find. but do far, all working as expected.

**Pull request merged**
