### PR TITLE
Pin pip to 9.0.3 until OctoPrint 1.3.9 is released

### LINKED ISSUE #526: Incompatibility between pip 10+ (as provided on OctoPi 0.15.0) and OctoPrint up to 1.3.8 causes issues
#### What were you doing?

Installing a plugin from the plugin repository in OctoPrint 1.3.8 running on OctoPi 0.15.0. Steps to reproduce:

1. flash a fresh OctoPi 0.15.0 & boot it up
2. complete OctoPrint's first run wizard
3. install any plugin from OctoPrint's built in plugin manager (e.g. Custom Control Editor)
4. restart OctoPrint

#### What did you expect to happen?

OctoPrint reporting the plugin as installed. No warnings in the log on install & on restart.

#### What happened instead?

OctoPrint couldn't detect which plugin was installed and showed it as "Unknown" in the popup message. `octoprint.log` showed:

```
2018-05-03 05:16:29,062 - py.warnings - WARNING - /home/pi/oprint/local/lib/python2.7/site-packages/octoprint/plugin/core.py:1643: UserWarning: No PKG-INFO found for package: octoprint_HeaterTimeout
  warnings.warn('No PKG-INFO found for package: %s' % self.package_name)
```

both after install and on startup during plugin detection. This is caused by a change in metadata of python packages installed through pip versions 10 and up, see also foosel/OctoPrint#2625. This problem is fixed on the `maintenance` branch.

Since OctoPi 0.15.0 however ships with OctoPrint 1.3.8 and pip 10 and is hence affected out of the box (and will stay affected on new installs even after OctoPrint 1.3.9 with the fix is released, until the user updates the included OctoPrint instance), I propose a release of OctoPi 0.15.1 with the `chroot_script` adjusted so that it upgrades the venv pip to 9.0.3 instead of the newest 10.0.1. I can provide a PR that does this, however I'm unsure against which branch since the change should naturally be done against 0.1.5.0, not current `devel` which might already contain more changes. So please tell me how to proceed here.

#### Did the same happen when running OctoPrint in safe mode?

Plugin installations and third party plugins as installed via pip are disabled when OctoPrint runs in safe mode, so this cannot be reproduced there, however it is a verified issues with pip 10+ installed plugins as seen in the above linked OctoPrint ticket.

#### Version of OctoPi

0.15.0

0.14.0 is still fine, as is an OctoPi 0.15.0 with pip downgraded to 9.0.3 via `~/oprint/bin/pip install pip==9.0.3`.

#### Printer model & used firmware incl. version

Issue isn't related to printer communication

#### Screenshot(s)/video(s) showing the problem:

```
2018-05-04 13:00:35,944 - py.warnings - WARNING - C:\Devel\OctoPrint\OctoPrint\src\octoprint\plugin\core.py:1643: UserWarning: No PKG-INFO found for package: octoprint_autoselect
  warnings.warn('No PKG-INFO found for package: %s' % self.package_name)

2018-05-04 13:00:35,969 - octoprint.plugins.pluginmanager - WARNING - The plugin was installed successfully, but couldn't be found afterwards to initialize properly during runtime. Please restart OctoPrint.
```

image

I have read the FAQ

### PR DESCRIPTION
**Pull request by foosel**
Fixes #526

### CODE REVIEW

**Comment by guysoft** [comment]
Now got to move the build system to build minor branch

**Comment by guysoft** [comment]
Pushed to 0.15.x, which seems more logical of a name. And also incremented the version.

**Comment by foosel** [comment]
Maks sense. And sorry, forgot the version increment. And timeline for the image build? Or was it already done and I just didn't notice yet (very likely)?

**Comment by foosel** [comment]
Are you sure you upped the version? At least here on Github it still shows as 0.15.0 on that branch

**Comment by guysoft** [comment]
Look at 0.15.x branch.

Nightly build:
https://storage.googleapis.com/octoprint/2018-05-08_2018-04-18-octopi-stretch-lite-0.15.1.zip
MD5: ``4600d24c0618376c2a10c1507b8ba990``

Sorry for not opening an RC, this week is insane

**Comment by guysoft** [comment]
My bad, didn't push :speak_no_evil:

**Pull request merged**
