### PR TITLE
Fix #619 Shutdown requires network

### LINKED ISSUE #619: Shutdown requires network
Hi 

Ive written an Plugin for Octoprint [Octoprint MyStrom Switch](https://github.com/da4id/OctoPrint-MyStromSwitch) this Plugin integrates a wifi switch into Octoprint. This switch has an feature that allows to tell the switch turn off relais in xy seconds. This is very useful in combination with octopi. With that i can shutdown the printer and after 60 seconds if the raspberry pi is shutted down it turns off power as well. 

There is one Problem if I issue the command `sudo shutdown -h now` the network connection is shutted down bevore the plugin gets the shutdown event. Therefore the wifiswitch wont turn off. 
[see this Issue](https://github.com/da4id/OctoPrint-MyStromSwitch/issues/17)

The fix is to add `# Required-Stop: networking` to the init script

I think this could be useful for other plugins too.

### PR DESCRIPTION
**Pull request by da4id**

### CODE REVIEW

**Comment by guysoft** [comment]
Its commented out, I am not sure if this has any effect on the distro. 
I see you wrote more info #619 here
@foosel Any input on this?

**Comment by foosel** [comment]
Sounds reasonable to me!

**Comment by guysoft** [comment]
Do the commented out lines there have any impact? Is it a header for something else?

**Comment by guysoft** [comment]
Accepting, it either has no effect or fixes the issue. But would value some context here what is using it so we know in the future.

**Comment by foosel** [comment]
> Is it a header for something else?

Yes, for LSB

**Comment by foosel** [comment]
Though long term we should prolly just switch over from the sys v initscript to a systemd unit file anyhow. Even got one prepped, just no time for a PR so far. I'll try to remember in January, last day in the office today for this year and still some other stuff to take care of.

**Comment by da4id** [comment]
Yes its a header an not commented out!
for details see [Debian Wiki LSB Init Scripts](https://wiki.debian.org/LSBInitScripts)

Thanks for merging!

This change makes shure, that octoprint is stopped bevore the linux networking service is stopped. This is useful if an Octoprint component requires working network connection inside the on shuttdown event. 
For example for a wifi switch to tell that octoprint is shutting down. Could also be useful for an monitoring / logging application on another server to notify that octoprint is shutting down now (homeautomation or whatever).

In future it could alse be helpful to have `$local_fs` as Required-Stop dependecy. If someone want to write something down to the filesystem on shutdown or change any gpio state for a proper shutdown.

**Pull request merged**
