### PR TITLE
HLS proxying and tuning

### PR DESCRIPTION
**Pull request by chudsaviet**
* Proxied HLS through HAProxy to avoid CORS issues and streamline web serving.
* Made JPEG frames writing atomic.
* Tuned HLS stream.

### CODE REVIEW

**Comment by guysoft** [comment]
@foosel opinions?

**Comment by chudsaviet** [comment]
There is a PR to OctoPrint on review by @foosel - https://github.com/OctoPrint/OctoPrint/pull/3647
Also I have created a OctoPi branch with Octoprint HLS support and HLS by default, for testing purposes - https://github.com/chudsaviet/OctoPi/tree/feature/devel_with_octoprint_hls .

**Comment by foosel** [comment]
In principle fine. Haven't yet had a chance to look at the PR on my side though, RC stuff takes precedence.

**Comment by guysoft** [comment]
@chudsaviet Does this PR depend on the OctoPrint one?

**Comment by chudsaviet** [comment]
No, it does not.

**Comment by guysoft** [comment]
Ok, then, seems nice, merging.

**Comment by chudsaviet** [comment]
Thank you!

**Pull request merged**
