### PR TITLE
added scripts for TouchUI boot-to-browser (7" touchscreen related)

### PR DESCRIPTION
**Pull request by idcrook**
#189

related to issue #189 (add support for the official PiTFT 7" touch screen) 

scriptified steps in [TouchUI plugin boot to browser](https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Setup:-Boot-to-Browser)

Changes made in `OctoPi/src/filesystem/home/pi/scripts`
Added:
- `boot-to-browser-touchui` bash script
- `plugin_status.py` python script

### CODE REVIEW

**Comment by BillyBlaze** [comment]
Just a head-up, the guide has been changed to support OctoPi 0.13 and can be found [here](https://github.com/BillyBlaze/OctoPrint-TouchUI/wiki/Setup:-Boot-to-Browser-(OctoPi-or-Jessie-Light))

**Comment by idcrook** [comment]
I'm going to close this PR, as it appears it won't be merged/updated.

**Comment by guysoft** [comment]
You could keep it open, it might become relevent

**Comment by idcrook** [comment]
I was doing some personal GitHub site cleanup. 

Instead I think I'll just keep my forked repo up on GitHub, and if it does warrant a revisit, it'll be there.

**Pull request closed without merging**
