### PR TITLE
Update vagrant documentation and remove unnecessary sudo

### PR DESCRIPTION
**Pull request by nbelakovski**

### CODE REVIEW

**Comment by guysoft** [comment]
Sudo is required because vagrant needs to edit ``/etc/exports`` to work. Which is owed by root

**Comment by nbelakovski** [comment]
I didn't have that issue running on my mac, and I checked that the /etc/exports file is indeed owned by root. I checked the contents of the file and it indeed has some vagrant related text in it. Perhaps this was an issue with earlier version of vagrant? Could you try to re-set things up in your environment and confirm that you still get the issue?

**Comment by nbelakovski** [comment]
I tried to verify this on a virtual install of linux, but getting vagrant to work in that was a pain. I was, however, able to determine that sudo is also not necessary for the plugin install (at least, it can succeed without sudo, dunno if something down the line requires that command to be run with sudo, but I doubt it). For what it's worth, I didn't install the nfs stuff on my mac when I ran this and it worked fine. If you have the time, maybe you could check to see if uninstalling that plugin and unloading nfs still work? It would be super cool if there were even fewer dependencies to getting this work :)

By the way, great job on this thing. It does feel like a bit of a beast to use at times, but I was able to successfully use it to create an OS that launches a wifi hotspot on bootup, so one can just ssh into the pi without having keyboard or mouse or having to modify the network settings on the image itself. But I digress :)

**Comment by guysoft** [comment]
Ok,
So I am getting conflicting information in the output.
In the output console I get:
```
==> default: Exporting NFS shared folders...
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
```

However I do seem to be able to create a userspace vagrant and run an installation form it.
So before I can merge this safely there might be a requirement that we are missing to be able to edit /etc/exports. And I would like to document it before other users start getting problems.

**Comment by nbelakovski** [comment]
I ran it again and watched for those two lines, immediately after them it asked me for my password. Perhaps you had entered yours recently and that's why it went through. I also double-checked the permissions of my /etc/exports and it was -rw-r--r--, so it's not like mine was editable by outside groups.

**Comment by guysoft** [comment]
This PR got stuck, and seems less relevant now since everyone moved to use docker. Unless there is some good reason I am closing it.

**Pull request closed without merging**
