### PR TITLE
🐛 Remove mjpg-streamer from pi home and relocate to /opt/mjpg-streamer

### PR DESCRIPTION
**Pull request by foosel**
It's executed as root so it shouldn't live in a user directory (potential for abuse w/ image access).

Move it to /opt/mjpg-streamer, include symlink at old location for backwards compatibility.

cc @kantlivelong

### CODE REVIEW

**Comment by foosel** [comment]
Oops, something's not right there, force push incoming

**Comment by foosel** [comment]
Fixed, ready for review.

**Comment by guysoft** [comment]
Okie

**Comment by guysoft** [comment]
Okie

**Pull request merged**
