### PR TITLE
Addition of a torrent download option

### PR DESCRIPTION
**Pull request by Duckle29**
As a torrent offers redundancy (multiple seeders) and also offers higher download rates (multiple downloads from multiple sources) I thought having a torrent would help in the download of this.

If you want me to make and seed new torrents for new versions, I can do that :)

### CODE REVIEW

**Comment by dcousens** [comment]
Where is this magnet link these days?
The standard mirror is super slow for me despite a high bandwidth connection.

**Comment by guysoft** [comment]
Are you using the google cloud links?

Guy

**Comment by dcousens** [comment]
I am using https://octopi.octoprint.org/download/stable/octopi-jessie-lite-0.13.0.zip

**Comment by guysoft** [comment]
What speeds are you getting exactly? It takes around 2 minutes to download
500~ MB here from that link.

**Comment by dcousens** [comment]
1 hour for the download here,  equivalent torrent was 2 minutes.

**Comment by seefood** [comment]
Guy, how expensive can it be to stick it all on S3? Plus they even support torrents...

**Comment by guysoft** [comment]
That depends who pays

**Comment by seefood** [comment]
patreon the damn thing, or get a company to fund it. how much can the bill be? more than a few dozen $$$ a month?

**Comment by foosel** [comment]
Ok... everyone please check their attitude a bit here.

This is a free project, based on work done by @guysoft in his free time. The hosting currently is provided partially by companies and partially I'm paying for it out of my own pocket.

Even "a few dozen $$$ a month" stack up, so just demanding to add to the bill because a handful of people demand a torrent but aren't willing to look into that themselves is - sorry - quite entitled.

And just for the record, last I checked prices on S3 run around 0.032€ per GB. Even when just calculating with a measly 1TB traffic per month of seed-only traffic you'd already be at a monthly bill over 30€. And that would only be one data center, ideally you'd need to spread across multiple of those.

**Comment by seefood** [comment]
$0.0125 per GB for S3 IA, and that's when spread around 3 AZs. it doesn't have to be replicated across the globe since it's pretty fast, plus Torrents are supported. $30-$40 is no big deal, I'll chip in 5% of that without a blink, and I only ever downloaded 2 images so far, but the project is worth it (and I'm also on your Patreon, Gina). people who use 3D printers usually have some spare income to spend on good causes like this, I'm not too worried.
OTOH, Guy, if you don't want to bother with this, I don't mind fixing this up myself. I'll set up the S3 bucket, produce a link page every time you upload with torrent and direct download links, and if the costs are indeed more than a few $ a month, I'll set up a paypal or something. Works for you?

**Comment by dcousens** [comment]
(or we could just put up the builds as a magnet URI?)
I'll happily re-seed,  just thought I'd mention it so a process could come about as the the automatic generation of the torrent each time a release occurs.

**Comment by guysoft** [comment]
@ia42 Willing to try

**Comment by foosel** [comment]
If someone tells me how to have a torrent magnet thing be generated automatically, I'll happily make this part of the release script I run through when updating the "latest" link on octopi.octoprint.org and publish next to the regular download link (also on octoprint.org proper). Or alternatively the S3 .torrent link from @seefood. Or both, whatever.

**Comment by dumle29** [comment]
@foosel Here's a script that I use for a podcast: http://pastebin.com/6N9cBd30

It's invoked by this incron line: `/srv/deluge/storage IN_CLOSE_WRITE  /bin/sh /srv/deluge/autoTorrentScript $#`
which runs whenever a file is added to the storage folder, and calls the script with the name of the file that was added ($# wildcard)

It creates a torrent with mktorrent, and uses a range of public trackers. 

It then creates an email, with the text "Torrent attached" and the torrent file attached. I use MSMTP to send this, which requires a separate SMTP server, for which I use my gmail smtp server I think. Been a while since I set it up. 

As for auto seeding the torrent, I'm using deluge, where i have enabled the auto add torrents from folder feature, and set the path to the folder seen in the script.

The result is that any file put in /srv/deluge/storage, will have a torrent generated for it, then an email generated and sent, with the torrent attached, then the file is moved to the download directory of deluge, and the torrent is copied to an auto add folder, that starts the torrent. Deluge will detect the file, verify it's integrity, and then seed.

**Comment by dumle29** [comment]
Okay, so again I came back to having to download octopi. and it's gotten fairly snappy by now, but I'd like to help offer a torrent option, to save on the bandwidth requirements for guy, fossel, and the companies helping.

To that end, I've made a python script, that checks the link to the latest octopi, and, if there's a new version out, downloads it, makes a torrent for it, adds that torrent to a torrent client and seeds it, and hosts the torrent file here: http://flipflapflop.top/octopi/

The script I'm using can be found here: http://paste.ubuntu.com/23814954/
as you can see I'm using: http://py3createtorrent.readthedocs.io/en/latest/user.html

you can also see that I tried to use magnet uris in there, but couldn't get that to work sadly.

I hope it can help lighten the load :)

**Comment by dumle29** [comment]
I have also gotten RSS to work now. The script generates an RSS feed that supplies both magnet links and links to the torrent file for friendly seeders who want to help out when the torrent is created :)

**Comment by dumle29** [comment]
Code is now available on github as well https://github.com/dumle29/torrentGen

**Pull request merged**
