### PR TITLE
Install OctoPrint from network via pip

### PR DESCRIPTION
**Pull request by foosel**
OctoPrint 1.3.6+ no longer relies on git for updating itself,
so there's really no use to ship with a full blown git checkout
any more.

In case people miss that however, there's a README.txt in place
that tells people how to get it back if they do need it.

### CODE REVIEW

**Comment by guysoft** [comment]
I know you wrote it and all - but is it better for users to have there? Will it make switching to dev branches any harder?
I am not sure how much it effects the image size-wise.

**Comment by John-Mc** [comment]
I use it to install some other things needed for use in the classroom where I volunteer. It definitely makes things simpler for me, but I don't use it often, and mine is an unusual situation, so if it makes a significant difference on image size (or for other considerations), just having the readme telling me how to get it back would be acceptable.

**Comment by foosel** [comment]
It will make switching to dev branches a bit more work, but only once (and in actually looking into changing that too somehow). And keeping a local checkout that is no use in 90% of cases just feels wrong to me somehow - I'm less worried about space consumption here and more about people getting confused by this checkout that is not actually active. Eg it will stay at the shipped version unless the user regularly pulls, so if they then switch to it they'd get an outdated version all of a sudden. And modifying it wouldn't do anything (this already causes confusion now). So keeping it would most likely only cause support overhead which I'm in desperate need to cut down on.

Getting the checkout back is literally three commands of needed, plus adding a path to the software update config if commit tracking is to be enabled. Want me to add something like the install-desktop script for that, just like create-octoprint-checkout instead?

In general going away from git as update mechanism was long overdue. It caused a ridiculous amount of problems due to corrupted git checkouts.

@John-Mc the OctoPrint git checkout, or git?

**Comment by guysoft** [comment]
A script is always a good idea. They cost nothing to ship and they make sure users didn't execute the wwrong thing.

**Comment by foosel** [comment]
Ok, I'll add one to the PR in a bit.

**Comment by John-Mc** [comment]
Sorry, I misread the original post. Getting rid of the octoprint git checkout does not bother me at all.

**Comment by foosel** [comment]
`scripts/add-octoprint-checkout` added.

**Comment by guysoft** [comment]
Not good, I am getting now:
```
/distro/modules/octopi/config: line 5: curl: command not found
```

From 
```
[ -n "$OCTOPI_OCTOPRINT_ARCHIVE" ] || OCTOPI_OCTOPRINT_ARCHIVE=$(curl -s https://api.github.com/repos/foosel/OctoPrint/releases/latest | grep "zipball_url" | cut -d : -f 2,3 | tr -d \" | tr -d ,)
```

And I really don't want to add this to the vagrant dependencies, because I want to make the vagrant system update with the custompios-update-paths command soon.

**Comment by foosel** [comment]
You base image doesn't have `curl`? O_O

**Comment by guysoft** [comment]
These are the dependencies which I rather keep minimal. 
https://github.com/guysoft/CustomPiOS/blob/CustomPiOS/src/dist_generators/dist_example/src/vagrant/setup.sh

You can do the same with wget:

```
wget -q -O - https://api.github.com/repos/foosel/OctoPrint/releases/latest
```
Should I push this or you want to do the honors?

**Comment by foosel** [comment]
Feel free to, I'm currently up to my head in other stuff. However, I also used `curl` for fetching the latest yq a couple lines further down, see [here](https://github.com/guysoft/OctoPi/blob/devel/src/modules/octopi/config#L31). 

Personally I'd prefer `curl` over `wget` here and am surprised that it doesn't come included with the base image.

Btw, if your goal is to keep those dependencies at a minimum, why p7zip *and* regular zip?

**Comment by guysoft** [comment]
Because armbian distribute all official builds in 7z format and before we added that users had a hard time un7zing and zipping back.
And wget does what you want just fine. Until its required for functionality I don't see why to

**Comment by foosel** [comment]
My point wasn't "why is p7zip added there" but rather, doesn't p7zip also support ZIP, making the `zip` and `unzip` redundant? And I don't want to argue here, I was just curious.

**Comment by guysoft** [comment]
Yws, it does, we could remove them.

**Pull request merged**
