### PR TITLE
Auto reconnect WLAN after a lost connection

### LINKED ISSUE #145: OctoPi not reconnecting Wi-Fi when network goes down
I had some issue with my modem/router lately and it needed a restart. I was printing using OctoPi (1.2.6) and I'm using a Wi-Fi dongle to communicate with it. When the network was up again OctoPi did not reconnect (the print was OK though). The only way to get it to reconnect, without power cycling the Pi, was to unplug and replug the Wi-Fi dongle.

I have another RPi running [OSMC](https://osmc.tv/), which behaved correctly and reconnected immediately, with the same type of Wi-Fi dongle.

It seems a connection drop and reconnect is [not](http://www.lynsayshepherd.com/blog/2014/06/27/keeping-the-raspberry-pi-connected-via-wi-fi/) [something](http://itsbrent.net/2014/05/fixing-raspberry-pi-wifi-dropping/) [trivial](http://unix.stackexchange.com/questions/224881/wi-fi-drops-its-really-complicated-to-autoreconnect-raspberry-pi-with-octopi). So I prefer asking here for the best way to handle this for OctoPi.

### PR DESCRIPTION
**Pull request by Salandora**
This is my attempt to fix #145, it uses a script from the wpa_supplicant package.

### CODE REVIEW

**Comment by guysoft** [comment]
Did you test this?

**Comment by Salandora** [comment]
Of course I did but just with a PI2.
Building from source worked and after flashing the image the wlan always reconnected (router turned off and on again multiple times).

**Comment by Manchineel** [comment]
guysoft/foosel,

I am operating OctoPrint on a RPI3 (using internal wifi adapter) with OctoPi 0.14.  I have experienced a problem with my PI losing its connection to my network.  The print keeps going, but I can not control it via wifi.  It seems like commit #145 should have fixed this.  Is there a way I can confirm this on my install?  Full disclosure - I am not a Linux savvy user.  Thanks for your help.

**Comment by guysoft** [comment]
You are likely experiencing #464 .

**Comment by Manchineel** [comment]
It is not an issue of not being able to connect at all.  I am connecting just fine.  However, at points during a very long print, the pi seems to lose connection to my local wifi and does not reconnect.  This means the only way I have to connect to the RPI to pause, or stop the print is locally.  I understand that there are ways to check for a connection, and if none, and reboot just the wifi (http://alexba.in/blog/2015/01/14/automatically-reconnecting-wifi-on-a-raspberrypi/).  It sounded like #145 implemented something similar.  I was just wondering how I might confirm it was working.

**Comment by guysoft** [comment]
@Manchineel No, that script you shared tests connectivity by pinging `8.8.8.8` server. You can see in #145 @foosel against testing internet connectivity to confirm connectivity on a local network.  I think irs wise too.
This script uses a script provided in wpa supplicant package.

**Comment by Manchineel** [comment]
I think we are complete agreement.  I am not necessarily interested in connectivity with the internet as much as I am with my local network.  The primary question is how to force the RPI wifi adapter to reconnect to the local network once it loses its connection.  It seems like setting a condition that allows it confirm its connected on some interval, and if no connection is found to restart the wifi adapter could solve this problem.

**Comment by trackdork** [comment]
@Manchineel - Just experienced this issue for the first time myself.  Looong print going, had to reboot router due to other issues and my Pi3 running octoprint is not showing up on the network.

**Comment by willsteinmetz** [comment]
I think I may be experiencing something similar. The wireless network will stay up for about a minute. I can see when I run `iwconfig` that it is connected to the specified network in octopi-network.conf. After about a minute, when I run `iwconfig` again, it is no longer connected. I'm pretty close to my router so I'm not sure that that would be the problem. If I restart `wlan0` with `sudo ifdown wlan0` and `sudo ifup wlan0` and then check `iwconfig` again, it'll stay up for about a minute and then drop again. None of the plethora of things I've Googled have helped at all.

Not sure if it'll help at all, but I'm using a Raspberry Pi 3 with the internal wifi chip. I just got it today and it is my first foray into the world of Raspberry Pi so I'm a bit at a loss of how to fix it. Also, if I plug it in with an ethernet cable, it works fine but this won't be an option when it goes to live in the room I'm planning to place it.

**Comment by guysoft** [comment]
@willsteinmetz unrelated to this issue. This issue talks about disconnect after a long time connected.

1. Make sure you are using a ppower supply of at least 2Avand a GOOF USB cable.
2. The chipset on the pi 3 is a weak, some users reported connecting an external dongle solved their problems

**Comment by willsteinmetz** [comment]
@guysoft I double-checked and my power supply is using 2.5A. I installed a USB wifi dongle that was designed for the Raspberry pi and it was doing the same thing. It wasn't until I reformatted and used the octopi-wpa-supplicant file that it wanted to work right.

**Pull request merged**
