### PR TITLE
HLS V4L2 M2M encoder

### PR DESCRIPTION
**Pull request by chudsaviet**
1. Building FFmpeg from source for HLS.
2. Using V4L2 M2M encoder. 

Tested on Raspberry Pi OS 32bit and 64bit. CPU load on Rpi4 is around 10%.

### CODE REVIEW

**Comment by guysoft** [comment]
Thanks for your contribution!

**Comment by chudsaviet** [comment]
@guysoft , I see this pull request caused build time to increase from 10 minutes to 2 hours. I can go disable unnecessary codecs from ffmpeg build, but it won’t help dramatically.

**Comment by cp2004** [comment]
I wonder if there is a way ffmpeg could be built once, and then the binary just downloaded from somewhere as part of the OctoPi image? Since it is building from a specific commit it seems like it shouldn't have to re-build every time.

**Comment by guysoft** [comment]
Could be built and exported once using ``copy_and_export_folder`` from CustomPiOS. Then loaded if it already exists from a web server.

**Comment by guysoft** [comment]
@chudsaviet
Hey,
This is currently breaking the nightly, because the nightly build is done on a raspberrypi running a 32bit userspace and a 64bit kernel.

The ffmpeg build determines the build arch according to the kernel used and this causes the build to fail.

There should be a flag to tell it explicitly based on on what CustomPiOS is building what arch to build for.

Attaching a filed log:

```
cd FFmpeg-FFmpeg-9450f75
+ ./configure --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-ffplay --disable-ffprobe
install prefix            /usr/local
source path               .
C compiler                gcc
C library                 glibc
ARCH                      aarch64 (genericcd FFmpeg-FFmpeg-9450f75
+ ./configure --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-ffplay --disable-ffprobe
install prefix            /usr/local
source path               .
C compiler                gcc
C library                 glibc
ARCH                      aarch64 (generic
```
[consoleText.txt](https://github.com/guysoft/OctoPi/files/9120274/consoleText.txt)

**Comment by guysoft** [comment]
I think there should be a way to pass the configure what arch to build for.

**Comment by chudsaviet** [comment]
Yes, I believe configure uses arch command to determine architecture.

**Comment by guysoft** [comment]
Fixed, builds on both now

**Comment by guysoft** [comment]
Current devel branch exports ffmpeg HLS that is built to the workspace folder. So we could have some logic that you place that inside ``OctoPi/src/modules/octopi/filesystem/hls`` . Then the build script can use unpack and check it it has a pre-built binary or not. So you could have a shorter build time.

**Comment by chudsaviet** [comment]
I see. Exact mechanism is not the problem.  
The problem is managing binaries and their security. I'm not very eager to go this deep. Also, after next FFmpeg version will be released, we will be able just to use ffmpeg from OS repo.
I was working on next things:
1. Minimizing FFmpeg build options, so its builds much faster.
2. Ensuring that in CustomPiOS /tmp is mounted as tmpfs, so the build is faster. Can you help me on this?

**Comment by guysoft** [comment]
It seems like it would just be best to wait after FFmpeg version will be released.

1. I am not sure what to remove
2. You don't necessarily have access to tmpfs. It depends on your build environment.

**Comment by guysoft** [comment]
We might want to add instructions how to activate it if you would like to add that

**Comment by chudsaviet** [comment]
Yeah, sorry, I had much work last couple of weeks.  
“activate it” - what do you mean?
“I am not sure what to remove” - there are dozens of codecs in ffmpeg, and for HLS, we don’t need most of them. We can build a limited ffmpeg just for HLS, and use standard ffmpeg from repository for everything else.

**Comment by guysoft** [comment]
I mean that I am not sure the setting in [octopi.txt](https://github.com/guysoft/OctoPi/blob/devel/src/modules/octopi/filesystem/boot/octopi.txt#L89) is documented.

**Comment by chudsaviet** [comment]
It was experimental, so I haven't documented it in the past.  
Which document shall I put the info to?

**Comment by guysoft** [comment]
It should go https://github.com/guysoft/OctoPi/wiki
But that also needs some care ATM, I don't know if its worth sending you there to document. Unless you think it would help.

**Pull request merged**
