### PR TITLE
Added support for zsync, compression is an rsyncable gzip and a sha1 checksum support is added

### PR DESCRIPTION
**Pull request by seefood**
Part of the solution to Issue #79

### CODE REVIEW

**Comment by guysoft** [comment]
1. I don't think we want to publish as tar.gz because most windows users don't have a way to untar files. Raspberrypi.org use zip files as well.
2. At the moment Jenkins creates an md5sum before uploading, but it seems to be a bit problematic.

I think we should move to sha1, but not sure that tar.gz is a good idea as the exclusive release format.
I can give you access to the Jenkins build if you want to have a look: http://gnet.homelinux.com:8080/job/OctoPi/

**Comment by guysoft** [comment]
Mind you, we are thinking about having a dedicated server, then we could zsync to it, and then zip the file on the other side. cc @foosel

**Comment by seefood** [comment]
1. No tar, only gz, and many windows tools open it, the FOSS 7zip as one example.
2. the change is not for no reason, it's the gzip --rsyncale option that makes all the difference, and allows users to get a delta and save time. right now it takes about 3 hours to download an image, This idea is meant to shorten that time to a dozen minutes, hopefully, if you already have an older image.
3. if Jenkins creates an md5sum, just add it to the nightlies directory then... otherwise how can we test the file?
4. zsync is not rsync, it's rsync-like, and the cool thing is it works with any web server, nothing needs to be installed on the server, and you get rsync-like delta transfer (not as optimal, but pretty good)

**Comment by seefood** [comment]
boo!

**Comment by guysoft** [comment]
We moved to cloud storage and that does not happen anymore.
And its super fast.

**Comment by guysoft** [comment]
RaspberryPi OS moved to store files as .xz compression. So possibly we could move to that.

**Pull request closed without merging**
