### PR TITLE
Accept to specify a camera device with "-d /dev/v4l/*" in "/boot/octpi.txt"

### PR DESCRIPTION
**Pull request by usk-johnny-s**
Changes for #596

### CODE REVIEW

**Comment by usk-johnny-s** [comment]
I add new feature that Load multiple camera configuration files.

If you use multiple camera, store multiple configration files in "/boot/octpi.txt/*.txt".
configration file format is same as original "/boot/octpi.txt".

**Comment by guysoft** [comment]
Looks cool, have you tested this?
Are their any limitations/other changes I should know about before merging it?

**Comment by guysoft** [comment]
Ok noted this will break current usage because you are turning octopi.txt in to a folder.
Usually if you want to have a configuration folder you should call it ``octopi.conf.d/``
I can't find where its written in a spec, but this explains it:
http://blog.siphos.be/2013/05/the-linux-d-approach/

**Comment by usk-johnny-s** [comment]
> Looks cool, have you tested this?

I should say no, because I don't set-up a image building environment now.
I tested just my modified script, by overwrite '/root/bin/webcamd' on Raspberry Pi with OctoPi 0.16.0.

> Ok noted this will break current usage because you are turning octopi.txt in to a folder.

My modified script checks that a type of '/boot/octopi.txt' is  a file or not.
Then, load '/boot/octopi.txt' if file, otherwise try to load '/boot/octopi.txt/*.txt' .

https://github.com/guysoft/OctoPi/blob/920bd8df903925d69da8b224c0a73e4c693a87d0/src/modules/octopi/filesystem/home/root/bin/webcamd#L25-L29

> Usually if you want to have a configuration folder you should call it octopi.conf.d/

Yes I know. My thought is compatibility on migration.
But, you indicated priority that a directory naming policy is higher than a compatibility. I will modify my script.

**Comment by guysoft** [comment]
Ok, once you change it to ``octopi.conf.d/`` I'll merge it so we can test it.

**Comment by usk-johnny-s** [comment]
I changed to "/boot/octopi.conf.d/" and built boot image on Ubuntu x64.
It can boot my Raspberry Pi 3B+. But it has something strange.
Even though I have not connected a video device, it is existed that  /dev/video10, 11, 12. it is diffarent between octopi v0.16.0 .
And althought I just connect pi-camera and reboot, /dev/video1 was added.

**Comment by guysoft** [comment]
If you are building against the latest base image, they might have changed driver stuff. Its fairly new and we didn't enough tests yet.

**Comment by usk-johnny-s** [comment]
'/dev/video10,11,12 and video1' issue is caused by raspbian (current 'https://downloads.raspberrypi.org/raspbian_lite_latest' is '2019-06-20-raspbian-buster-lite.zip')

I download previous raspbian ( 'https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2019-04-09/2019-04-08-raspbian-stretch-lite.zip' ) and build octopi boot image.
It looks same as octopi v0.16.0 with on my Raspberry Pi 3B+ . (nothing here is '/dev/video*', if not connected a video device, or only connect pi-camera.)

ref: https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=232684&p=1466567#p1466567

**Comment by usk-johnny-s** [comment]
camera="auto" for raspi-cam is not working. I will fix it.
And I plan to change webcamd startup mechanism from init.d to systemd.

**Comment by guysoft** [comment]
Ok, just ping me when you are ready for me to pull it

**Comment by usk-johnny-s** [comment]
I was done fix issue of "auto" and chane to sytemd.
New boot image works fine.

**Comment by guysoft** [comment]
Ok, so is this ready to pull?

**Comment by usk-johnny-s** [comment]
Yes please.

**Comment by guysoft** [comment]
Ok merged cc @foosel Note this moves ``octopi.txt`` in to ``conf.d/octopi.txt``.
I am not sure I am happy with that, but I guess we could also just move it back.

**Comment by foosel** [comment]
> Note this moves `octopi.txt` in to `conf.d/octopi.txt`.

You are aware that that will wreak **havoc** with our userbase? I'm sure that I'm *not* happy with that.

**Comment by guysoft** [comment]
@foosel Ok, managed to have a look and fix it.

@usk-johnny-s if you want to have a look and confirm this works for you it would help.

**Pull request merged**
